import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import {NuqsAdapter} from 'nuqs/adapters/next/app';
import './globals.css';
import {Header} from './components/Header';
import {Footer} from './components/Footer';
import {ContactButtons} from './components/ContactButtons';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen max-w-120 relative mx-auto`}
      >
        <NuqsAdapter>
          <ContactButtons />
          <Header />
          {children}
          <Footer />
        </NuqsAdapter>
      </body>
    </html>
  );
}
